make automation paths configurable in rspec
ccutrer/openhab-jrubyscripting pull request #120
Opened 2022-12-10 17:03 UTC by ktgeek

automation paths can be configured in the rspec helper file by adding config.openhab_automation_search_paths. The default is to check OPENHAB_CONF/automation/ruby and
OPENHAB_CONF/automation/jsr223/ruby/personal

2022-12-12 19:00 UTC, ccutrer requested changes
docs/example of setting the config to add a staging dir?

2022-12-12 19:17 UTC, ktgeek commented on lib/openhab/rspec.rb
> +    "#{org.openhab.core.OpenHAB.config_folder}/automation/jsr223/ruby/personal"
Cool, I can change that easily.

I'll add some docs on setting it.  (I did say it was a WIP :) )

That said, I need to figure out why the specs were seeing a file twice...

2022-12-28 20:46 UTC, ccutrer approved these changes

2023-01-01 00:16 UTC, merged

2023-01-01 13:27 UTC, jimtng commented
Somehow this caused rspec to fail https://github.com/ccutrer/openhab-jrubyscripting/actions/runs/3814321429

2023-01-01 13:43 UTC, jimtng commented
> Somehow this caused rspec to fail https://github.com/ccutrer/openhab-jrubyscripting/actions/runs/3814321429

My apologies, this wasn't the cause.