prevent QuantityType comparison against Numeric
ccutrer/openhab-jrubyscripting pull request #21
Opened 2022-11-12 07:04 UTC by jimtng

Proposed changes so that comparison between QuantityType and String can be supported in a personal library using String#coerce.

The issue was because String responds to `to_d` which prevents QuantityType <=> from calling other.coerce. Furthermore, we should prevent comparison between QuantityType and Numeric because it's ambiguous

2022-11-13 17:01 UTC, ccutrer requested changes
In general, for seeing how comparisons _should_ behave, do `"string" <=> 5`, etc.

2022-11-14 00:26 UTC, jimtng commented on lib/openhab/core/types/quantity_type.rb
> +          else
I've refactored it to avoid putting `if` inside the case-else block

2022-11-14 00:27 UTC, jimtng commented on spec/openhab/core/types/quantity_type_spec.rb
> +      expect { ten_f == "10 °F" }.to raise_exception(ArgumentError)
fixed

2022-11-14 00:28 UTC, jimtng commented on spec/openhab/core/types/quantity_type_spec.rb
> +      expect(unit("°F") { ten_c == 50 }).to be true
Thanks, that's much nicer!

2022-11-14 00:28 UTC, jimtng commented on spec/openhab/core/types/quantity_type_spec.rb
> +      expect { ten_c > 3 }.to raise_exception(ArgumentError)
fixed

2022-11-14 00:29 UTC, jimtng commented on lib/openhab/core/types/quantity_type.rb
> +        # @raise [ArgumentError] if the two values are incomparable.
fixed

2022-11-14 01:29 UTC, merged